### ISSUE TITLE
train and test .csv files

### ISSUE THREAD

**Issue by PromptForge** [skandavivek/transformerQA-finetuning#1]
Hello,
thank you for sharing your work.
Could you please inform me where can be found these particular train.csv and test.csv files?

**Comment by skandavivek** [comment]
It is here:

https://github.com/megagonlabs/SubjQA

**Comment by PromptForge** [comment]
> It is here:
> 
> https://github.com/megagonlabs/SubjQA

Thank you very much for the quick reply!
